version: "2.1"
services:
  server_bucket:
    build:
      context: .
      dockerfile: ./bucket/Dockerfile
    ports:
      - "8080:4000"
    privileged: true
    cap_add:
        - SYS_ADMIN
    depends_on:
      db_bucket:
        condition: service_healthy
    environment:
      # UPLOAD Variables
      - UPLOAD_PATH=./public/bucket/images
      - MEDIA_PROXY_PATH=/bucket/images
      # BUCKET paths
      - FUSE_MOUNT_DIR=./public/bucket
      - FUSE_BUCKET_NAME=node-chat-bucket
      - GOOGLE_APPLICATION_CREDENTIALS=/server/credentials.json
      - DB_HOST=db_bucket

  db_bucket:
    image: mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "echo", "show dbs", "|", "mongo"]
      interval: 5s
      timeout: 10s
      retries: 3
    command: mongod --smallfiles
